### ISSUE TITLE
Vertical and horizontal maximize no longer working

### ISSUE THREAD

**Issue by peterryan** [raspberrypi-ui/openbox-stretch#1]
Hello,
You probably know this isn't working given that  a previous commit comment explicitly says as much:
https://github.com/raspberrypi-ui/openbox-stretch/commit/de67618ea9e3e22e7623d56530934d3a3fc272e0

...but this breaks the ability to easily maximize a window to (say) left/right side of the screen and then be able to unmaximize it back to it's old size.

I have the following in my ~/.config/openbox/lxde-pi-rc.xml file:
```
<keybind key="W-Left">
    <action name="MoveResizeTo">
        <x>0</x>
    </action>
    <action name="Maximize">
        <direction>vertical</direction>
    </action>
</keybind>

<keybind key="W-Right">
    <action name="MoveResizeTo">
        <x>-0</x>
    </action>
    <action name="Maximize">
        <direction>vertical</direction>
    </action>
</keybind>

<keybind key="W-Up">
  <action name="Maximize"/>
</keybind>

<keybind key="W-Down">
  <action name="Unmaximize"/>
</keybind>
```
which works very nicely in Raspbian Jessie but not in Stretch due to the above change.

I've had a dig around, but I wasn't able to fathom what your changes were doing, so I've not got any useful patch (I did try, honest!). My fork just reverts a small part of your changes and, for me, that solves the problem.
https://github.com/peterryan/openbox-stretch/commit/295bd5f1a2ca1b51bae78c3903d9150271b446e3

All the best,

Peter.

**Comment by spl237** [comment]
I made this change to fix a nasty race condition in Openbox for Stretch, whereby the Ctrl-Alt-Left and Ctrl-Alt-Right key combinations gave a window with one edge which oscillated between two positions. (Openbox is full of code which teeters on the verge of race conditions - this is not the first similar problem I have found...) It may be that your change reintroduces the race condition; on the other hand, it might be that the remaining parts of my change are enough to fix it. I'll need to try it - if it doesn't reintroduce the race condition, I'll pull your change in.

**Comment by spl237** [comment]
I've just tried your change, and unfortunately it does reintroduce the race condition on maximising a window to the left or right half of the screen.

The problem is caused by the concept of being able to maximise a window in a single direction, and this is slightly illogical to start with - it causes confusion in things like the icons on the window title bar; if a window is maximised in one direction and not the other, should the maximise icon be white and allow maximisation in the other direction, or should it be greyed? Etc. Unidirectional maximising is a bit of a hack, which is why it doesn't work too well - it's not something offered by Windows or MacOS.

While I can understand that this is frustrating as it has broken a workflow you were used to using, I don't think I can pull in your change; notwithstanding the race condition on C-A-Left and Right, I don't think unidirectional window maximising is a good thing from a user interface design perspective. Please accept my apologies for this!
