### ISSUE TITLE
multi desktop options,

### ISSUE THREAD

**Issue by dobkeratops** [raspberrypi-ui/openbox-stretch#3]
ok I do realise I can just switch to another window manager.
I was just surprised by the responses I got here, and rapid shut down of discussion.

_'We chose not to have multiple desktops, and wont re-enable it'_

I totally understand disabling it by default.

Yet on my latest raspbian install, **I click the mid-mouse button on the desktop and I get the option to 'add new desktop'**, and I get the desktop-mousewheel support (which then leads me to want the mousewheel on desktop-pager , mousewheel 'take to desktop' option, and you already have an option _in the UI_ which leads to a sub-optimal double-click+mousewheel on titlebar option, wasting 2 controls for the same feature ('shade') . **We could adjust that existing option remap the mousewheel aswell, surely** ).

I'm not asking for it to be enabled out of the box. but it appears to still be here as an option for people who want it. You appear to be saying "we dont want people to use it". I'm suggesting some tweaks which would make what is already there better.

Yes , multi-desktops can be confusing *when they're not fully integrated*. Contrary to what you said, Apple have fully integrated multi-desktops with the concept of 'maximised/fullscreen apps', with a UI that is very natural for people who've come from phones (swiping to flick through screens, showing thumbnails). Their **'maximise button'** initiates a scrolling transition of the current window into it's own desktop.

Whilst I'm not suggesting that we try to emulate all of that, I do beleive with just a few tweaks it's possible for multi-desktop support to be more intuitive, and an unambiguous benefit. To me it's the graphical equivalent of the 'unix philosophy' i.e. the ability to build a workflow from different apps, i.e. 'a peice of documentation in a web browser, a text editor, a terminal -> all on one desktop for one particular task'

Windows used to have a button 'show desktop' which hides everything. What I imagine is this function upgraded: 'make sure there's an empty desktop, and switch to it'. Gnome-Shell kind of has this idea, dynamically creating/destroying desktops such that there's always one empty. If you want to restore everything it should be visible on the taskbar (e..g the taskbar and 'alt-tab' menu could show stuff from all desktops, until they run out of space..) . you currently *can* do this, it's just 2 steps ('create the desktop then switch to it').

I'm willing to write code for this - As I mentioned in the other post, I've made my own version of XFWM, but without co-operation and consensus from maintainers such work is wasted (it gets annoying to keep a fork going for a few lines changed) so I learned to discuss first before investing my time.

**Comment by spl237** [comment]
As I said before, we have taken the decision to not encourage the use of multiple desktops. They are enabled by default in vanilla LXDE, and as soon as I took over the design of the Raspberry Pi Desktop, they were removed from the default configuration. Very few people complained...

Multiple desktops are an anachronism. They are an artefact of a time when large screen high-resolution monitors were prohibitively expensive. They are a usability nightmare, particularly for new users, who are the primary target of the RPD environment. It is far too easy to open an application, accidentally hit a button to switch to a new desktop, and have everything vanish for no reason. This is not helpful, particularly for beginners.

The UI items you point out above are simply a legacy of the multiple desktop support which is built into Openbox. I could have gone through the code and removed them, but they remain for the benefit of users like yourself who do wish to re-enable multiple desktop support. As it is, if you want multiple desktop support, you are free to re-enable it by installing the Openbox configuration manager, adding more desktops, and customising the user interface if desired - which, in the case of the option you were requesting yesterday, is a simple change to the Openbox configuration file as I showed, and does not require code changes.

I reiterate - we have thought carefully about this decision. For our target audience, it is the right one. We have not prevented users such as yourself from re-enabling multiple desktop support (nor do we intend to do so), but we do not encourage it. We have no interest in improving a feature whose use we discourage.

Please try to bear in mind our target audience - because it is clear from what you have written that you are not a typical member of it. We are trying to make the Linux desktop environment accessible and approachable for people who have never used it - and who in some cases have never used a computer before. I am not disputing that you find multiple desktops convenient for your particular use case, but it is my responsibility to make the decisions which make life best for the majority of our users, and not supporting or encouraging multiple desktops is the right decision for them.
